version: '3.8'

services:
    coba_docker-dockerfile:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - APP_NAME=coba_docker-dockerfile
            - APP_PORT=8080
        ports:
            - "5051:8080"

    coba_docker-image:
        image: coba_docker
        environment:
            - APP_NAME=coba_docker-image
            - APP_PORT=8080
        ports:
            - "5052:8080"
